name: ML_pymc3_
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.5
  - ipython=8.27.0
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.7
  - numpy=1.25.2
  - pymc=5.10.4
  - pymc-base=5.10.4
  - python=3.11.10
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
